# Generated by Django 3.2.2 on 2021-05-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210511_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymaster',
            name='Descrpt',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
